web:
    build: .
    environment:
        MYENV: EXAMPLE
    volumes:
        - .:/code
web_migrate:
    extends:
        service: web
    command: python3 manage.py migrate
chat_run:
    extends:
        service: web
    command: python3 manage.py migrate
web_run:
    extends: docker run -p 6379:6379 -d redis:5
        service: web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"
